name: Test React Build

on:
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.4
    - run: yarn install --frozen-lockfile
      shell: bash
    - run : yarn build
      shell: bash